### ISSUE TITLE
Maven code generator plugin inlcuding a sample project. 

### ISSUE THREAD

**Issue by rwperrott** [daanvdh/JavaForger#5]
A sensible Maven code generator plugin must be usable, by default, with only declaration, any need for user provided controller Java class/code breaks that, and the too sparse documentation here suggests that issue.

**Comment by daanvdh** [comment]
This is currently not a maven code generator plugin. You will have to manually select an input class and execute a main method. Currently this project is targeted to insert boiler plate code into existing classes, and keep the possibility to change it manually if needed. 

Having said that, this project can easily be extended to become such a maven plugin. You would need custom parameterized class annotation where the parameter links an existing class to a JavaForgerConfiguration object (which includes the template). Then a class scanner should select the annotated classes and execute the given configurations on them.

**Comment by rwperrott** [comment]
Lost interest.
